wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647762297
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 3
      - 8
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: LSTM
batch_size:
  desc: null
  value: 4
dataset:
  desc: null
  value: weizmann450
epochs:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.0001
loss_function:
  desc: null
  value: categorical_crossentropy
